name: Test Multiple python versions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      # Install pip and pytest
      - name: Install dependencies
        run: |
          make install
      - name: Test with pytest
        run: |
          make test
      - name: Lint with pylint
        run: |
          make lint
      - name: Format code  Python Black
        run: |
          make format
